#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "#koditi"

# Short bio or description (displayed in the header)
description: Sumber maklumat utama software developer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/koditi.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: koditi
  flickr:
  github: koditi
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: koditi
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  telegram:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: koditi

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://koditi.my/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
permalink: /:title/
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  input: GFM
  syntax_highlighter: rouge

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

include:
    - .well-known
    
excerpt_separator: "<!--more-->"

tag_page_layout: tag_page
tag_page_dir: .
tag_permalink_style: pretty

timezone: Asia/Kuala_Lumpur

twitter_username: koditi

authors:
  kamal:
    name:           Kamal Mustafa
    bio_short:      Lead Engineer at Xoxzo Inc. Develop web applications in Python/Django. Interested in open source and tech talent development.
    bio_full:       <a href="https://www.xoxzo.com/">Xoxzo.com</a> provide API services for developer to develop messaging and voice based application. The postings on this site are my own and don't necessarily represent my employer's positions, strategies or opinions. I can be reached via Twitter <a href="https://twitter.com/k4ml">@k4ml</a>.
    gravatar:       dab3052b18c86b0884341d9c2c67a4f3
    pic:            https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAX4AAAAJGM3ZjdkN2M3LTBkZmMtNDZlZi1hZGI4LTEzZTk4MTNiOTYyMQ.jpg
  robotys:
    name:           Izwan Wahab
    bio_short:      Sr Developer at Xentral Methods Sdn Bhd. Focusing on Web Development in PHP/Codeigniter/Laravel. 
    bio_full:       Interest in broad areas of discipline (physic, music, design, graphic, marketing etc). Avid reader/collector on non-fiction business-sy books. Xentral Methods is my employer. Any posting here was my own opinion without any representation on `em.
    gravatar:       d5646f6ce71d05740d4aef1a1a85e913
    pic:            http://notabisnes.net/assets/img/robotys.jpeg
